// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// Bookmark defines model for Bookmark.
type Bookmark struct {
	CreatedAt   time.Time            `json:"createdAt"`
	Description *string              `json:"description,omitempty"`
	Favicon     *string              `json:"favicon,omitempty"`
	FolderId    *openapi_types.UUID  `json:"folderId,omitempty"`
	Id          openapi_types.UUID   `json:"id"`
	ImageUrl    *string              `json:"imageUrl,omitempty"`
	IsFavorite  bool                 `json:"isFavorite"`
	TagIds      []openapi_types.UUID `json:"tagIds"`
	Title       string               `json:"title"`
	Url         string               `json:"url"`
}

// CreateBookmarkInput defines model for CreateBookmarkInput.
type CreateBookmarkInput struct {
	Description *string               `json:"description,omitempty"`
	Favicon     *string               `json:"favicon,omitempty"`
	FolderId    *openapi_types.UUID   `json:"folderId,omitempty"`
	ImageUrl    *string               `json:"imageUrl,omitempty"`
	IsFavorite  *bool                 `json:"isFavorite,omitempty"`
	TagIds      *[]openapi_types.UUID `json:"tagIds,omitempty"`
	Title       string                `json:"title"`
	Url         string                `json:"url"`
}

// CreateFolderInput defines model for CreateFolderInput.
type CreateFolderInput struct {
	Name string `json:"name"`
}

// CreateTagInput defines model for CreateTagInput.
type CreateTagInput struct {
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// FetchMetadataInput defines model for FetchMetadataInput.
type FetchMetadataInput struct {
	Url string `json:"url"`
}

// FetchMetadataResponse defines model for FetchMetadataResponse.
type FetchMetadataResponse struct {
	Description *string `json:"description,omitempty"`
	Favicon     *string `json:"favicon,omitempty"`
	ImageUrl    *string `json:"imageUrl,omitempty"`
	Title       string  `json:"title"`
}

// Folder defines model for Folder.
type Folder struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshInput defines model for RefreshInput.
type RefreshInput struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterInput defines model for RegisterInput.
type RegisterInput struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Tag defines model for Tag.
type Tag struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// UpdateBookmarkInput defines model for UpdateBookmarkInput.
type UpdateBookmarkInput struct {
	Description *string               `json:"description,omitempty"`
	Favicon     *string               `json:"favicon,omitempty"`
	FolderId    *openapi_types.UUID   `json:"folderId,omitempty"`
	ImageUrl    *string               `json:"imageUrl,omitempty"`
	IsFavorite  *bool                 `json:"isFavorite,omitempty"`
	TagIds      *[]openapi_types.UUID `json:"tagIds,omitempty"`
	Title       *string               `json:"title,omitempty"`
	Url         *string               `json:"url,omitempty"`
}

// UpdateFolderInput defines model for UpdateFolderInput.
type UpdateFolderInput struct {
	Name string `json:"name"`
}

// UpdateTagInput defines model for UpdateTagInput.
type UpdateTagInput struct {
	Name string `json:"name"`
}

// ListBookmarksParams defines parameters for ListBookmarks.
type ListBookmarksParams struct {
	// IsFavorite Filter by favorite status
	IsFavorite *bool `form:"isFavorite,omitempty" json:"isFavorite,omitempty"`

	// HasFolder true = only bookmarks assigned to a folder, false = only bookmarks with no folder
	HasFolder *bool `form:"hasFolder,omitempty" json:"hasFolder,omitempty"`

	HasTags *bool `form:"hasTags,omitempty" json:"hasTags,omitempty"`

	// ID of the last bookmark from the previous batch
	LastID *openapi_types.UUID `form:"last_id,omitempty" json:"last_id,omitempty"`

	// Number of items per page
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginInput

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshInput

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterInput

// CreateBookmarkJSONRequestBody defines body for CreateBookmark for application/json ContentType.
type CreateBookmarkJSONRequestBody = CreateBookmarkInput

// UpdateBookmarkJSONRequestBody defines body for UpdateBookmark for application/json ContentType.
type UpdateBookmarkJSONRequestBody = UpdateBookmarkInput

// FetchMetadataJSONRequestBody defines body for FetchMetadata for application/json ContentType.
type FetchMetadataJSONRequestBody = FetchMetadataInput

// CreateFolderJSONRequestBody defines body for CreateFolder for application/json ContentType.
type CreateFolderJSONRequestBody = CreateFolderInput

// UpdateFolderJSONRequestBody defines body for UpdateFolder for application/json ContentType.
type UpdateFolderJSONRequestBody = UpdateFolderInput

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagInput

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTagInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Login
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// RefreshToken Exchange refresh token for new access token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Register Register a new user
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// ListBookmarks List all bookmarks for the authenticated user
	// (GET /bookmarks)
	ListBookmarks(w http.ResponseWriter, r *http.Request, params ListBookmarksParams)
	// CreateBookmark Create a bookmark
	// (POST /bookmarks)
	CreateBookmark(w http.ResponseWriter, r *http.Request)
	// DeleteBookmark Delete a bookmark
	// (DELETE /bookmarks/{id})
	DeleteBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateBookmark Update a bookmark
	// (PATCH /bookmarks/{id})
	UpdateBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// RemoveBookmarkFolder Remove a bookmark from its folder (unset folderId to null)
	// (DELETE /bookmarks/{id}/folder)
	RemoveBookmarkFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// FetchMetadata Scrape metadata from a URL
	// (POST /fetch-metadata)
	FetchMetadata(w http.ResponseWriter, r *http.Request)
	// ListFolders List all folders for the authenticated user
	// (GET /folders)
	ListFolders(w http.ResponseWriter, r *http.Request)
	// CreateFolder Create a folder
	// (POST /folders)
	CreateFolder(w http.ResponseWriter, r *http.Request)
	// DeleteFolder Delete a folder
	// (DELETE /folders/{id})
	DeleteFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateFolder Update a folder
	// (PATCH /folders/{id})
	UpdateFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListTags List all tags for the authenticated user
	// (GET /tags)
	ListTags(w http.ResponseWriter, r *http.Request)
	// CreateTag Create a tag
	// (POST /tags)
	CreateTag(w http.ResponseWriter, r *http.Request)
	// DeleteTag Delete a tag
	// (DELETE /tags/{id})
	DeleteTag(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateTag Update a tag
	// (PATCH /tags/{id})
	UpdateTag(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Login
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshToken Exchange refresh token for new access token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register Register a new user
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListBookmarks List all bookmarks for the authenticated user
// (GET /bookmarks)
func (_ Unimplemented) ListBookmarks(w http.ResponseWriter, r *http.Request, params ListBookmarksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateBookmark Create a bookmark
// (POST /bookmarks)
func (_ Unimplemented) CreateBookmark(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteBookmark Delete a bookmark
// (DELETE /bookmarks/{id})
func (_ Unimplemented) DeleteBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateBookmark Update a bookmark
// (PATCH /bookmarks/{id})
func (_ Unimplemented) UpdateBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RemoveBookmarkFolder Remove a bookmark from its folder (unset folderId to null)
// (DELETE /bookmarks/{id}/folder)
func (_ Unimplemented) RemoveBookmarkFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// FetchMetadata Scrape metadata from a URL
// (POST /fetch-metadata)
func (_ Unimplemented) FetchMetadata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListFolders List all folders for the authenticated user
// (GET /folders)
func (_ Unimplemented) ListFolders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateFolder Create a folder
// (POST /folders)
func (_ Unimplemented) CreateFolder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteFolder Delete a folder
// (DELETE /folders/{id})
func (_ Unimplemented) DeleteFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateFolder Update a folder
// (PATCH /folders/{id})
func (_ Unimplemented) UpdateFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTags List all tags for the authenticated user
// (GET /tags)
func (_ Unimplemented) ListTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateTag Create a tag
// (POST /tags)
func (_ Unimplemented) CreateTag(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteTag Delete a tag
// (DELETE /tags/{id})
func (_ Unimplemented) DeleteTag(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateTag Update a tag
// (PATCH /tags/{id})
func (_ Unimplemented) UpdateTag(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBookmarks operation middleware
func (siw *ServerInterfaceWrapper) ListBookmarks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookmarksParams

	// ------------- Optional query parameter "isFavorite" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isFavorite", r.URL.Query(), &params.IsFavorite, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "isFavorite"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isFavorite", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "hasFolder" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hasFolder", r.URL.Query(), &params.HasFolder, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hasFolder"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hasFolder", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "hasTags" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hasTags", r.URL.Query(), &params.HasTags, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hasTags"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hasTags", Err: err})
		}
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last_id", r.URL.Query(), &params.LastID, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last_id", Err: err})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookmarks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBookmark operation middleware
func (siw *ServerInterfaceWrapper) CreateBookmark(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBookmark(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBookmark operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookmark(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBookmark operation middleware
func (siw *ServerInterfaceWrapper) UpdateBookmark(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveBookmarkFolder operation middleware
func (siw *ServerInterfaceWrapper) RemoveBookmarkFolder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveBookmarkFolder(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FetchMetadata operation middleware
func (siw *ServerInterfaceWrapper) FetchMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FetchMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFolders operation middleware
func (siw *ServerInterfaceWrapper) ListFolders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFolders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFolder operation middleware
func (siw *ServerInterfaceWrapper) CreateFolder(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFolder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFolder operation middleware
func (siw *ServerInterfaceWrapper) DeleteFolder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFolder(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateFolder operation middleware
func (siw *ServerInterfaceWrapper) UpdateFolder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFolder(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTag operation middleware
func (siw *ServerInterfaceWrapper) CreateTag(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTag(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTag operation middleware
func (siw *ServerInterfaceWrapper) DeleteTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTag(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTag operation middleware
func (siw *ServerInterfaceWrapper) UpdateTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTag(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookmarks", wrapper.ListBookmarks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookmarks", wrapper.CreateBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/bookmarks/{id}", wrapper.DeleteBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/bookmarks/{id}", wrapper.UpdateBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/bookmarks/{id}/folder", wrapper.RemoveBookmarkFolder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/folders", wrapper.ListFolders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/folders", wrapper.CreateFolder)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/folders/{id}", wrapper.DeleteFolder)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/folders/{id}", wrapper.UpdateFolder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags", wrapper.ListTags)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tags", wrapper.CreateTag)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tags/{id}", wrapper.DeleteTag)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/tags/{id}", wrapper.UpdateTag)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/fetch-metadata", wrapper.FetchMetadata)
	})

	return r
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse AuthResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse ErrorResponse

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse ErrorResponse

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListBookmarksRequestObject struct {
	Params ListBookmarksParams
}

type ListBookmarksResponseObject interface {
	VisitListBookmarksResponse(w http.ResponseWriter) error
}

type ListBookmarks200JSONResponse []Bookmark

func (response ListBookmarks200JSONResponse) VisitListBookmarksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBookmarkRequestObject struct {
	Body *CreateBookmarkJSONRequestBody
}

type CreateBookmarkResponseObject interface {
	VisitCreateBookmarkResponse(w http.ResponseWriter) error
}

type CreateBookmark201JSONResponse Bookmark

func (response CreateBookmark201JSONResponse) VisitCreateBookmarkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBookmark400JSONResponse ErrorResponse

func (response CreateBookmark400JSONResponse) VisitCreateBookmarkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteBookmarkRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteBookmarkResponseObject interface {
	VisitDeleteBookmarkResponse(w http.ResponseWriter) error
}

type DeleteBookmark200JSONResponse struct {
	Success *bool `json:"success,omitempty"`
}

func (response DeleteBookmark200JSONResponse) VisitDeleteBookmarkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteBookmark404JSONResponse ErrorResponse

func (response DeleteBookmark404JSONResponse) VisitDeleteBookmarkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBookmarkRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateBookmarkJSONRequestBody
}

type UpdateBookmarkResponseObject interface {
	VisitUpdateBookmarkResponse(w http.ResponseWriter) error
}

type UpdateBookmark200JSONResponse Bookmark

func (response UpdateBookmark200JSONResponse) VisitUpdateBookmarkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBookmark404JSONResponse ErrorResponse

func (response UpdateBookmark404JSONResponse) VisitUpdateBookmarkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveBookmarkFolderRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type RemoveBookmarkFolderResponseObject interface {
	VisitRemoveBookmarkFolderResponse(w http.ResponseWriter) error
}

type RemoveBookmarkFolder200JSONResponse Bookmark

func (response RemoveBookmarkFolder200JSONResponse) VisitRemoveBookmarkFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveBookmarkFolder404JSONResponse ErrorResponse

func (response RemoveBookmarkFolder404JSONResponse) VisitRemoveBookmarkFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type FetchMetadataRequestObject struct {
	Body *FetchMetadataJSONRequestBody
}

type FetchMetadataResponseObject interface {
	VisitFetchMetadataResponse(w http.ResponseWriter) error
}

type FetchMetadata200JSONResponse FetchMetadataResponse

func (response FetchMetadata200JSONResponse) VisitFetchMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type FetchMetadata400JSONResponse ErrorResponse

func (response FetchMetadata400JSONResponse) VisitFetchMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListFoldersRequestObject struct {
}

type ListFoldersResponseObject interface {
	VisitListFoldersResponse(w http.ResponseWriter) error
}

type ListFolders200JSONResponse []Folder

func (response ListFolders200JSONResponse) VisitListFoldersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFolderRequestObject struct {
	Body *CreateFolderJSONRequestBody
}

type CreateFolderResponseObject interface {
	VisitCreateFolderResponse(w http.ResponseWriter) error
}

type CreateFolder201JSONResponse Folder

func (response CreateFolder201JSONResponse) VisitCreateFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateFolder400JSONResponse ErrorResponse

func (response CreateFolder400JSONResponse) VisitCreateFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolderRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteFolderResponseObject interface {
	VisitDeleteFolderResponse(w http.ResponseWriter) error
}

type DeleteFolder200JSONResponse struct {
	Success *bool `json:"success,omitempty"`
}

func (response DeleteFolder200JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteFolder404JSONResponse ErrorResponse

func (response DeleteFolder404JSONResponse) VisitDeleteFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFolderRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateFolderJSONRequestBody
}

type UpdateFolderResponseObject interface {
	VisitUpdateFolderResponse(w http.ResponseWriter) error
}

type UpdateFolder200JSONResponse Folder

func (response UpdateFolder200JSONResponse) VisitUpdateFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFolder400JSONResponse ErrorResponse

func (response UpdateFolder400JSONResponse) VisitUpdateFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateFolder404JSONResponse ErrorResponse

func (response UpdateFolder404JSONResponse) VisitUpdateFolderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTagsRequestObject struct {
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse []Tag

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTagRequestObject struct {
	Body *CreateTagJSONRequestBody
}

type CreateTagResponseObject interface {
	VisitCreateTagResponse(w http.ResponseWriter) error
}

type CreateTag201JSONResponse Tag

func (response CreateTag201JSONResponse) VisitCreateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTag400JSONResponse ErrorResponse

func (response CreateTag400JSONResponse) VisitCreateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTagRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteTagResponseObject interface {
	VisitDeleteTagResponse(w http.ResponseWriter) error
}

type DeleteTag200JSONResponse struct {
	Success *bool `json:"success,omitempty"`
}

func (response DeleteTag200JSONResponse) VisitDeleteTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTag404JSONResponse ErrorResponse

func (response DeleteTag404JSONResponse) VisitDeleteTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTagRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateTagJSONRequestBody
}

type UpdateTagResponseObject interface {
	VisitUpdateTagResponse(w http.ResponseWriter) error
}

type UpdateTag200JSONResponse Tag

func (response UpdateTag200JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTag400JSONResponse ErrorResponse

func (response UpdateTag400JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTag404JSONResponse ErrorResponse

func (response UpdateTag404JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// RefreshToken Exchange refresh token for new access token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register Register a new user
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// ListBookmarks List all bookmarks for the authenticated user
	// (GET /bookmarks)
	ListBookmarks(ctx context.Context, request ListBookmarksRequestObject) (ListBookmarksResponseObject, error)
	// CreateBookmark Create a bookmark
	// (POST /bookmarks)
	CreateBookmark(ctx context.Context, request CreateBookmarkRequestObject) (CreateBookmarkResponseObject, error)
	// DeleteBookmark Delete a bookmark
	// (DELETE /bookmarks/{id})
	DeleteBookmark(ctx context.Context, request DeleteBookmarkRequestObject) (DeleteBookmarkResponseObject, error)
	// UpdateBookmark Update a bookmark
	// (PATCH /bookmarks/{id})
	UpdateBookmark(ctx context.Context, request UpdateBookmarkRequestObject) (UpdateBookmarkResponseObject, error)
	// RemoveBookmarkFolder Remove a bookmark from its folder (unset folderId to null)
	// (DELETE /bookmarks/{id}/folder)
	RemoveBookmarkFolder(ctx context.Context, request RemoveBookmarkFolderRequestObject) (RemoveBookmarkFolderResponseObject, error)
	// FetchMetadata Scrape metadata from a URL
	// (POST /fetch-metadata)
	FetchMetadata(ctx context.Context, request FetchMetadataRequestObject) (FetchMetadataResponseObject, error)
	// ListFolders List all folders for the authenticated user
	// (GET /folders)
	ListFolders(ctx context.Context, request ListFoldersRequestObject) (ListFoldersResponseObject, error)
	// CreateFolder Create a folder
	// (POST /folders)
	CreateFolder(ctx context.Context, request CreateFolderRequestObject) (CreateFolderResponseObject, error)
	// DeleteFolder Delete a folder
	// (DELETE /folders/{id})
	DeleteFolder(ctx context.Context, request DeleteFolderRequestObject) (DeleteFolderResponseObject, error)
	// UpdateFolder Update a folder
	// (PATCH /folders/{id})
	UpdateFolder(ctx context.Context, request UpdateFolderRequestObject) (UpdateFolderResponseObject, error)
	// ListTags List all tags for the authenticated user
	// (GET /tags)
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
	// CreateTag Create a tag
	// (POST /tags)
	CreateTag(ctx context.Context, request CreateTagRequestObject) (CreateTagResponseObject, error)
	// DeleteTag Delete a tag
	// (DELETE /tags/{id})
	DeleteTag(ctx context.Context, request DeleteTagRequestObject) (DeleteTagResponseObject, error)
	// UpdateTag Update a tag
	// (PATCH /tags/{id})
	UpdateTag(ctx context.Context, request UpdateTagRequestObject) (UpdateTagResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBookmarks operation middleware
func (sh *strictHandler) ListBookmarks(w http.ResponseWriter, r *http.Request, params ListBookmarksParams) {
	var request ListBookmarksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBookmarks(ctx, request.(ListBookmarksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBookmarks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBookmarksResponseObject); ok {
		if err := validResponse.VisitListBookmarksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBookmark operation middleware
func (sh *strictHandler) CreateBookmark(w http.ResponseWriter, r *http.Request) {
	var request CreateBookmarkRequestObject

	var body CreateBookmarkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBookmark(ctx, request.(CreateBookmarkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBookmark")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBookmarkResponseObject); ok {
		if err := validResponse.VisitCreateBookmarkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteBookmark operation middleware
func (sh *strictHandler) DeleteBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteBookmarkRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBookmark(ctx, request.(DeleteBookmarkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBookmark")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteBookmarkResponseObject); ok {
		if err := validResponse.VisitDeleteBookmarkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateBookmark operation middleware
func (sh *strictHandler) UpdateBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateBookmarkRequestObject

	request.Id = id

	var body UpdateBookmarkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBookmark(ctx, request.(UpdateBookmarkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBookmark")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateBookmarkResponseObject); ok {
		if err := validResponse.VisitUpdateBookmarkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveBookmarkFolder operation middleware
func (sh *strictHandler) RemoveBookmarkFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RemoveBookmarkFolderRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveBookmarkFolder(ctx, request.(RemoveBookmarkFolderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveBookmarkFolder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveBookmarkFolderResponseObject); ok {
		if err := validResponse.VisitRemoveBookmarkFolderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FetchMetadata operation middleware
func (sh *strictHandler) FetchMetadata(w http.ResponseWriter, r *http.Request) {
	var request FetchMetadataRequestObject

	var body FetchMetadataJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FetchMetadata(ctx, request.(FetchMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FetchMetadata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FetchMetadataResponseObject); ok {
		if err := validResponse.VisitFetchMetadataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFolders operation middleware
func (sh *strictHandler) ListFolders(w http.ResponseWriter, r *http.Request) {
	var request ListFoldersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFolders(ctx, request.(ListFoldersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFolders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFoldersResponseObject); ok {
		if err := validResponse.VisitListFoldersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateFolder operation middleware
func (sh *strictHandler) CreateFolder(w http.ResponseWriter, r *http.Request) {
	var request CreateFolderRequestObject

	var body CreateFolderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFolder(ctx, request.(CreateFolderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFolder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFolderResponseObject); ok {
		if err := validResponse.VisitCreateFolderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFolder operation middleware
func (sh *strictHandler) DeleteFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteFolderRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFolder(ctx, request.(DeleteFolderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFolder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFolderResponseObject); ok {
		if err := validResponse.VisitDeleteFolderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateFolder operation middleware
func (sh *strictHandler) UpdateFolder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateFolderRequestObject

	request.Id = id

	var body UpdateFolderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFolder(ctx, request.(UpdateFolderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFolder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateFolderResponseObject); ok {
		if err := validResponse.VisitUpdateFolderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(w http.ResponseWriter, r *http.Request) {
	var request ListTagsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx, request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		if err := validResponse.VisitListTagsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTag operation middleware
func (sh *strictHandler) CreateTag(w http.ResponseWriter, r *http.Request) {
	var request CreateTagRequestObject

	var body CreateTagJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTag(ctx, request.(CreateTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTagResponseObject); ok {
		if err := validResponse.VisitCreateTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTag operation middleware
func (sh *strictHandler) DeleteTag(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteTagRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTag(ctx, request.(DeleteTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTagResponseObject); ok {
		if err := validResponse.VisitDeleteTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTag operation middleware
func (sh *strictHandler) UpdateTag(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateTagRequestObject

	request.Id = id

	var body UpdateTagJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTag(ctx, request.(UpdateTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTagResponseObject); ok {
		if err := validResponse.VisitUpdateTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
